import {
    VerticalBox,
} from "std-widgets.slint";
import { PreviousIcon } from "../icons/PreviousIcon.slint";


export component PreviousButton inherits TouchArea {
    in-out property <physical-length> size: 48px;
    VerticalBox {
        padding:0px;
        PreviousIcon {
            width: size;
            height: size;
        }
    }
}



/*
export component HomeButton inherits Navigator {
    in property <image> image;
    in property <string> text;
    VerticalBox {
        Image {
            source: image;
            width: 150px;
            height: 150px;
        }

        Text {
            horizontal-alignment: center;
            text: text;
        }
    }
}
*/