import {
    VerticalBox,
} from "std-widgets.slint";

import { PlayIcon, PauseIcon } from "@lucide";


export component ToggleButton inherits TouchArea {
    in-out property <bool> is-playing: false;
    in-out property <physical-length> size: 48px;
    in-out property <color> stroke: #000000;
    in-out property <float> stroke-width: 2;
    VerticalBox {
        padding:0px;
        if is-playing: PauseIcon {
            stroke: stroke;
            size:size;
            stroke-width:stroke-width;
        }
        if !is-playing: PlayIcon {
            stroke: stroke;
            size:size;
            stroke-width:stroke-width;
       }
    }
}
