
import { VerticalBox, HorizontalBox } from "std-widgets.slint";
export component PiListItem inherits Rectangle {
    callback clicked;
    in-out property <image> icon;
    in-out property <bool> has-icon;
    in property <string> title;
    in property <string> subtitle;
    in property <string> description;

    border-radius: 3px;
    border-color: silver;
    border-width: 2px;


    VerticalBox {
        HorizontalBox {
            min-height:80px;
            spacing: 5px;
            padding:0px;
            if has-icon:
                Image {
                    width: 25%;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    source: icon;
                }


            VerticalBox {
                padding:0px;
                spacing: 0px;
                if !title.is-empty: Text {
                    font-size: 1.3rem;
                    font-weight: 1500;
                    vertical-alignment: center;
                    overflow:elide;
                    text: title;
                }
                if !subtitle.is-empty: Text {
                    font-size:0.8rem;
                    overflow:clip;
                    text: subtitle;
                }
                if !description.is-empty: Text {

                    wrap: word-wrap;
                    text: description;
                }
            }
        }
    }
    TouchArea {
        clicked => {
            root.clicked();
        }
    }
}