
import { VerticalBox, HorizontalBox } from "std-widgets.slint";
export component PiListItem inherits Rectangle {
    callback clicked;
    in-out property <image> icon;
    in-out property <bool> has-icon;
    in property <string> tagline;
    in property <string> title;
    in property <string> description;

    border-radius: 3px;
    border-color: silver;
    border-width: 2px;


    VerticalBox {
        HorizontalBox {
            min-height:80px;
            spacing: 5px;
            padding:0px;
            if has-icon:
                Image {
                    width: 25%;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    source: icon;
                }


            VerticalBox {
                padding:0px;
                spacing: 0px;

                if !tagline.is-empty: Text {
                    font-italic: true;
                    font-size:0.7rem;
                    overflow:clip;
                    text: tagline;
                }

                if !title.is-empty: Text {
                    font-size: 1.0rem;
                    font-weight: 1200;
                    vertical-alignment: center;
                    overflow:elide;
                    text: title;
                }

                if !description.is-empty: Text {
                    font-size:0.8rem;
                    wrap: word-wrap;
                    text: description;
                }
            }
        }
    }
    TouchArea {
        clicked => {
            root.clicked();
        }
    }
}