use std::geo2d::*;
use std::ops::*;
use std::math::*;

pub const WALL_THICKNESS = 1.25mm;
pub const RAIL_THICKNESS = 0.6mm;

pub const OUTER_DEPTH = 11.60mm;
pub const OUTER_WIDTH = 45.00mm;
pub const OUTER_HEIGHT = 88.75mm;

pub const CASE_HEIGHT = OUTER_HEIGHT - WALL_THICKNESS;
pub const CASE_DEPTH = OUTER_DEPTH - WALL_THICKNESS;

pub const INNER_DEPTH = OUTER_DEPTH - 2 * WALL_THICKNESS;
pub const INNER_WIDTH = OUTER_WIDTH - 2 * WALL_THICKNESS;
pub const INNER_HEIGHT = OUTER_HEIGHT - 2 * WALL_THICKNESS;

pub const DISPLAY_HOLE_WIDTH = 32.02mm + 1.98mm;
pub const DISPLAY_HOLE_HEIGHT = 48.02mm + 1.98mm;

pub const DISPLAY_GLASS_WIDTH = 38.34mm;
pub const DISPLAY_GLASS_HEIGHT = 56.37mm;
pub const DISPLAY_GLASS_THICKNESS = 1.36mm;

pub const DISPLAY_FRAME_WIDTH = 36.15mm;
pub const DISPLAY_FRAME_HEIGHT = 55.88mm;
pub const DISPLAY_FRAME_THICKNESS = 2.00mm;

pub const DISPLAY_RAIL_HEIGHT = DISPLAY_GLASS_HEIGHT + WALL_THICKNESS;



pub const DISPLAY_FULL_THICKNESS = DISPLAY_GLASS_THICKNESS + DISPLAY_FRAME_THICKNESS;

pub const LICHEE_PCB_WIDTH=22.90mm;
pub const LICHEE_PCB_HEIGHT=35.60mm;
pub const LICHEE_PCB_DEPTH=1.00mm;


pub part _DisplayGlass(height=DISPLAY_GLASS_HEIGHT) {
    width = DISPLAY_GLASS_WIDTH;
    depth = DISPLAY_GLASS_THICKNESS;
    Rect(width, height).extrude(depth);
}

pub part _DisplayFrame(height=DISPLAY_FRAME_HEIGHT) {
    width = DISPLAY_FRAME_WIDTH;
    depth = DISPLAY_FRAME_THICKNESS;
    Rect(width, height).extrude(depth);
}

pub part _DisplaySpacer(height=1mm) {
    {_DisplayGlass(height);_DisplayFrame(height);}.align(Z).union();
}

pub part Display() {
    {_DisplayGlass();_DisplayFrame();}.align(Z).union();
}

pub part ActionButton() {
    radius = 2.0mm;
    depth = WALL_THICKNESS / 2;
    holder = Circle(radius + 0.6mm).extrude(depth);
    button = Circle(radius).extrude(depth+1.5mm);

    {holder;button}.align(Z).union();
}

pub part _BackCoverRail() {
    width = INNER_WIDTH + RAIL_THICKNESS * 2;
    height = INNER_HEIGHT + RAIL_THICKNESS;
    depth = RAIL_THICKNESS;
    y_offset=RAIL_THICKNESS/2;
    Rect(width, height).extrude(depth);
}

pub part _BackCoverFiller() {
    width = INNER_WIDTH;
    height = INNER_HEIGHT;
    depth = WALL_THICKNESS - RAIL_THICKNESS;
    y_offset = RAIL_THICKNESS / 2;
    Rect(width, height).extrude(depth).translate(x=0mm, y=y_offset, z=0mm);
}

pub part _BackCoverBack() {
    {_BackCoverRail();_BackCoverFiller();}.align(Z).union();
}

pub part _BackCoverTop() {
    width = OUTER_WIDTH;
    height = WALL_THICKNESS;
    depth = OUTER_DEPTH;
    y_offset = CASE_HEIGHT/2 + RAIL_THICKNESS / 2;
    Rect(width, height).extrude(depth).translate(y=y_offset);
}

pub part BackCover() {
    z_offset = CASE_DEPTH;
    {_BackCoverTop();_BackCoverBack().translate(z=z_offset)}.union();
}

pub part _DisplayRailHousing() {
    width = INNER_WIDTH;
    height = DISPLAY_RAIL_HEIGHT;
    depth = DISPLAY_FULL_THICKNESS;
    Rect(width, height).extrude(depth);
}

pub part DisplayRail() {
    y_offset=0.87mm;
    {_DisplayRailHousing() - Display() - _DisplaySpacer(DISPLAY_FRAME_HEIGHT).translate(y=y_offset)}.align(Z).union();
}

pub part HomeButton() {
    radius = 5.00mm;
    depth = WALL_THICKNESS / 2;
    {Circle(radius + 2mm).extrude(depth);Circle(radius).extrude(depth);}.align(Z).union();
}


pub part UsbCPort() {
    border_width = 0.6mm;
    width = 8.4mm;
    height = 2.6mm;
    depth = 7.5mm;
    // Rect(width, height).extrude(depth).translate(x=0mm, y=0mm, z=0mm);
    y_offset = 0mm; // LICHEE_PCB_HEIGHT / 2 + 1mm;
    z_offset = 0mm; // LICHEE_PCB_DEPTH;
    RoundedRect(width, height, radius = border_width).extrude(depth).rotate(x=90°).align(Z).translate(x=0mm, y=y_offset, z=z_offset);
}


pub part _CaseFront() {
    width = OUTER_WIDTH;
    height = OUTER_HEIGHT;
    Rect(width, height).extrude(WALL_THICKNESS);
}

pub part _CaseWalls() {
    width = OUTER_WIDTH;
    height = OUTER_HEIGHT;
    Frame(width, height, WALL_THICKNESS)
            .extrude(CASE_DEPTH);
}

pub part _CaseFrame() {
    {  _CaseFront();  _CaseWalls();}.align(Z).union();
}


pub part _CaseFrameWithTopCoverRails() {
    y_offset = -RAIL_THICKNESS / 2;
    _CaseFrame() - BackCover().translate(y=y_offset);
}

pub part _CaseFrameWithRails() {
    y_offset = INNER_HEIGHT / 2 - DISPLAY_RAIL_HEIGHT / 2;
    z_offset = WALL_THICKNESS;
    {  _CaseFrameWithTopCoverRails(); DisplayRail().translate(y=y_offset,z=z_offset);}.union();
}

_CaseFrameWithRails();













pub part BottomWallHole() {
    width = INNER_WIDTH;
    height = WALL_THICKNESS;
    depth = OUTER_DEPTH - WALL_THICKNESS;
    y_offset = CASE_HEIGHT / 2  - WALL_THICKNESS / 2;
    z_offset = WALL_THICKNESS;
    Rect(width, height).extrude(depth).translate(x=0mm, y=y_offset, z=z_offset);
}

pub part DisplayHole() {
    width = DISPLAY_HOLE_WIDTH;
    height = DISPLAY_HOLE_HEIGHT;
    depth = WALL_THICKNESS;
    y_offset =  INNER_HEIGHT / 2 - DISPLAY_HOLE_HEIGHT / 2 - WALL_THICKNESS;
    Rect(width, height).extrude(depth).translate(x=0mm, y=y_offset, z=0mm);
}

pub part LicheeCenterSupport() {
    width=2mm;
    height=10mm;
    depth = INNER_DEPTH;
    Rect(width, height).extrude(depth);
}

pub part CaseWithDisplayHole() {
    Case() - DisplayHole()
}

pub part CaseWithDisplayHoleAndRail() {
    y_offset = OUTER_HEIGHT / 2 - DISPLAY_GLASS_HEIGHT / 2;
    {CaseWithDisplayHole(); DisplayRail().translate(y=y_offset, z=WALL_THICKNESS)}.union();
}

pub part TopCoverHole() {
    TopCover().translate(y=0mm, z=INNER_DEPTH+WALL_THICKNESS + 0mm);
}


pub part TopCoverUpsideDown() {
    x_offset=OUTER_WIDTH + 20mm;
    TopCover().translate(x=x_offset).reflect(Z).align(Z);
}

pub part LicheePcbShim() {
    width = LICHEE_PCB_WIDTH;
    height = LICHEE_PCB_HEIGHT;
    depth = LICHEE_PCB_DEPTH;
    Rect(width, height).extrude(depth).translate(x=0mm, y=0mm, z=0mm);
}



pub part LicheeMicroSdShim() {
    // width = 11.10mm;
    width = 14.00mm; // not centered, just make it bigger
    height = 1.50mm;
    depth = 16.00mm;
    y_offset = LICHEE_PCB_HEIGHT / 2 + 1mm;
    z_offset = -LICHEE_PCB_DEPTH - height / 2;
    Rect(width, height).extrude(depth).rotate(x=90°).align(Z).translate(x=0mm, y=y_offset, z=z_offset);
}

pub part LicheeShim() {
    UsbCPort();
    LicheePcbShim();
    LicheeMicroSdShim();
}

pub part CaseWithDisplayAndTopCoverHoles() {
    CaseWithDisplayHoleAndRail() - TopCoverHole();
}





pub part ActionButtonPositioned() {
    x_offset=-INNER_WIDTH / 2;
    z_offset=INNER_DEPTH / 2 + DISPLAY_FULL_THICKNESS / 2 + 1mm;

    ActionButton().rotate(x=90°, y=-90°).translate(x=x_offset, z=z_offset);
}

pub part ActionButtonRow() {
    top_offset = INNER_HEIGHT / 2 - WALL_THICKNESS / 2;

    power_offset = top_offset - 5mm;
    ActionButtonPositioned().translate(y=power_offset);

    vol_up_offset = power_offset - 15mm;
    ActionButtonPositioned().translate(y=vol_up_offset);

    play_offset = vol_up_offset - 7mm;
    ActionButtonPositioned().translate(y=play_offset);

    vol_down_offset = play_offset - 7mm;
    ActionButtonPositioned().translate(y=vol_down_offset);
}




pub part CaseWithDisplay_TopCover_LicheeHoles() {
    h = INNER_HEIGHT / 2 - LICHEE_PCB_HEIGHT;

    x_offset = INNER_WIDTH / 2 - LICHEE_PCB_WIDTH / 2 + WALL_THICKNESS / 2;
    y_offset = - (LICHEE_PCB_HEIGHT / 2) - h; //0mm; // -(INNER_HEIGHT - LICHEE_PCB_HEIGHT);
    z_offset = WALL_THICKNESS + DISPLAY_FULL_THICKNESS + 2mm; // INNER_HEIGHT / 2;


    CaseWithDisplayAndTopCoverHoles() - LicheeShim().rotate(x=180°).translate(x=x_offset,y=y_offset,z=z_offset);
}

pub part CaseWithDisplay_TopCover_Lichee_HomeButtonHoles() {

    x_offset = 0mm; // INNER_WIDTH / 2 - LICHEE_PCB_WIDTH / 2 + WALL_THICKNESS / 2;
    y_offset = -25mm; // - (LICHEE_PCB_HEIGHT / 2) - h; //0mm; // -(INNER_HEIGHT - LICHEE_PCB_HEIGHT);
    z_offset = 0mm; // + DISPLAY_FULL_THICKNESS + 2mm; // INNER_HEIGHT / 2;

    CaseWithDisplay_TopCover_LicheeHoles() - HomeButton().reflect(Z).align(Z).translate(x=x_offset,y=y_offset,z=z_offset);
}


pub part CaseWithDisplay_TopCover_Lichee_HomeButton_ActionButtonHoles() {

    CaseWithDisplay_TopCover_Lichee_HomeButtonHoles() - ActionButtonRow();
}


// y_offset=DISPLAY_INNER_HEIGHT/2;
// {Case();DisplayRail().translate(y=-15.6mm, z=WALL_THICKNESS)}.union() - DisplayHole();
// DisplayRailHousing() - Display();
// DisplayRail();
// DisplayRail().translate(y=15.6mm, z=WALL_THICKNESS);

// TopCover().rotate(180°);

// LicheeShim();
// HomeButton();
// ActionButton();

// #[export = "player-case.stl"]
// CaseWithDisplay_TopCover_Lichee_HomeButton_ActionButtonHoles();

// #[export = "player-backcover.stl"]
// TopCoverUpsideDown();

