use std::geo2d::*;
use std::ops::*;
use std::math::*;

pub const WALL_THICKNESS = 1.25mm;
pub const RAIL_THICKNESS = 0.6mm;

pub const OUTER_DEPTH = 11.60mm;
pub const OUTER_WIDTH = 45.00mm;
pub const OUTER_HEIGHT = 88.75mm;

pub const CASE_HEIGHT = OUTER_HEIGHT - WALL_THICKNESS;
pub const CASE_DEPTH = OUTER_DEPTH - WALL_THICKNESS;

pub const INNER_DEPTH = OUTER_DEPTH - 2 * WALL_THICKNESS;
pub const INNER_WIDTH = OUTER_WIDTH - 2 * WALL_THICKNESS;
pub const INNER_HEIGHT = OUTER_HEIGHT - 2 * WALL_THICKNESS;

pub const DISPLAY_HOLE_WIDTH = 32.02mm + 1.98mm;
pub const DISPLAY_HOLE_HEIGHT = 48.02mm + 1.98mm;

pub const DISPLAY_GLASS_WIDTH = 38.34mm;
pub const DISPLAY_GLASS_HEIGHT = 56.37mm;
pub const DISPLAY_GLASS_THICKNESS = 1.36mm;

pub const DISPLAY_FRAME_WIDTH = 36.15mm;
pub const DISPLAY_FRAME_HEIGHT = 55.88mm;
pub const DISPLAY_FRAME_THICKNESS = 2.00mm;

pub const DISPLAY_RAIL_HEIGHT = DISPLAY_GLASS_HEIGHT + WALL_THICKNESS;

pub const DISPLAY_FULL_THICKNESS = DISPLAY_GLASS_THICKNESS + DISPLAY_FRAME_THICKNESS;

pub const DISPLAY_INSET = (DISPLAY_GLASS_HEIGHT - DISPLAY_HOLE_HEIGHT) / 2;

pub const PCB_THICKNESS=1.00mm;

pub const LICHEE_PCB_WIDTH=22.90mm;
pub const LICHEE_PCB_HEIGHT=35.60mm;
pub const LICHEE_CAM_CONNECT_INSET=15.41mm;



pub const TP4057_PCB_WIDTH=12mm;
pub const TP4057_PCB_HEIGHT=16mm;

pub const MAX17043_PCB_WIDTH=10.3mm;
pub const MAX17043_PCB_HEIGHT=24.5mm;
pub const MAX17043_PCB_THICKNESS=1.6mm;

pub const MAX17043_HOLDER_BOTTOM_INSET=4.35mm;
pub const MAX17043_HOLDER_TOP_INSET=10mm;
pub const MAX17043_HOLDER_THICKNESS=PCB_THICKNESS + 0.6mm;




pub const MICRO_SD_WIDTH=14.00mm; // this technically is not correct (increased to make a bigger hole because the microSD slot is not centered)
pub const MICRO_SD_HEIGHT=16.00mm;
pub const MICRO_SD_DEPTH=1.50mm;

pub const USB_C_WIDTH=8.4mm;
pub const USB_C_HEIGHT=2.6mm;
pub const USB_C_DEPTH=7.5mm;





pub const PUSH_BUTTON_WIDTH = 6.15mm; // 6.10mm real width
pub const PUSH_BUTTON_HEIGHT = 3.95mm; // 3.91mm real height
pub const PUSH_BUTTON_DEPTH = 1.65mm; // 1.60mm real depth
pub const PUSH_BUTTON_DEPTH_KNOB = 2.25mm; // 2.18 real depth with knob pressed down, 2.40 with released knob

pub const PUSH_BUTTON_RADIUS = 0.95mm; // 0.90mm real radius
pub const PUSH_BUTTON_BTN_DEPTH = 0.85mm; // 0.80mm real depth

pub const PUSH_BUTTON_HOLDER_WIDTH = 7.2mm;
pub const PUSH_BUTTON_HOLDER_RAIL_WIDTH = 1mm;



// this is a workaround
pub const PUSH_BUTTON_REMOVE_HOLE_YES = 20mm;
pub const PUSH_BUTTON_REMOVE_HOLE_NO = 0mm;

pub const ACTION_BUTTON_DIAMETER = 3.5mm;
pub const ACTION_BUTTON_BASE_DIAMETER = 4.7mm;
pub const ACTION_BUTTON_BASE_DEPTH = WALL_THICKNESS / 2;
pub const ACTION_BUTTON_BUTTON_DEPTH = WALL_THICKNESS;
pub const ACTION_BUTTON_DEPTH = ACTION_BUTTON_BASE_DEPTH + ACTION_BUTTON_BUTTON_DEPTH;
pub const ACTION_BUTTON_RAIL_HEIGHT = OUTER_DEPTH - 2 * WALL_THICKNESS - DISPLAY_FULL_THICKNESS;
pub const ACTION_BUTTON_PIN_DEPTH = 0.3mm;



pub const BOTTOM_PART_HOLDER_WIDTH = INNER_WIDTH / 2 - WALL_THICKNESS;
pub const BOTTOM_PART_HOLDER_HEIGHT = INNER_HEIGHT - DISPLAY_RAIL_HEIGHT;
pub const BOTTOM_PART_HOLDER_THICKNESS = PCB_THICKNESS * 2;


pub const ANTENNA_WIDTH = 14.2mm;
pub const ANTENNA_HEIGHT = 31.63mm;



pub part _DisplayGlass(height=DISPLAY_GLASS_HEIGHT) {
    width = DISPLAY_GLASS_WIDTH;
    depth = DISPLAY_GLASS_THICKNESS;
    Rect(width, height).extrude(depth);
}

pub part _DisplayFrame(height=DISPLAY_FRAME_HEIGHT) {
    width = DISPLAY_FRAME_WIDTH;
    depth = DISPLAY_FRAME_THICKNESS;
    Rect(width, height).extrude(depth);
}

pub part _DisplaySpacer(height=1mm) {
    {_DisplayGlass(height);_DisplayFrame(height);}.align(Z).union();
}

pub part Display() {
    {_DisplayGlass();_DisplayFrame();}.align(Z).union();
}


pub part _BackCoverRail() {
    width = INNER_WIDTH + RAIL_THICKNESS * 2;
    height = INNER_HEIGHT + RAIL_THICKNESS;
    depth = RAIL_THICKNESS;
    // y_offset=RAIL_THICKNESS/2;
    Rect(width, height).extrude(depth);
}

pub part _BackCoverFiller() {
    width = INNER_WIDTH;
    height = INNER_HEIGHT;
    depth = WALL_THICKNESS - RAIL_THICKNESS;
    y_offset = RAIL_THICKNESS / 2;
    Rect(width, height).extrude(depth).translate(x=0mm, y=y_offset, z=0mm);
}

pub part _BackCoverBack() {
    {_BackCoverRail();_BackCoverFiller();}.align(Z).union();
}

pub part _BackCoverTop() {
    width = OUTER_WIDTH;
    height = WALL_THICKNESS;
    depth = OUTER_DEPTH;
    y_offset = CASE_HEIGHT/2 + RAIL_THICKNESS / 2;
    Rect(width, height).extrude(depth).translate(y=y_offset);
}

pub part BackCover() {
    z_offset = CASE_DEPTH;
    {_BackCoverTop();_BackCoverBack().translate(z=z_offset)}.union();
}

pub part LicheeCenterSupport() {
    width=WALL_THICKNESS * 2;
    height=WALL_THICKNESS * 2;
    depth = INNER_DEPTH;
    Rect(width, height).extrude(depth);
}

pub part LicheeCenterSupportPositioned() {
    x_offset=-WALL_THICKNESS / 2;
    y_offset=-BOTTOM_PART_HOLDER_HEIGHT - 0.5mm; // WALL_THICKNESS/2;
    LicheeCenterSupport().translate(y=y_offset, x=x_offset);
}

pub part _DisplayRailHousing() {
    width = INNER_WIDTH;
    height = DISPLAY_RAIL_HEIGHT;
    depth = DISPLAY_FULL_THICKNESS;

    lsupp = LicheeCenterSupportPositioned();



    {Rect(width, height).extrude(depth); lsupp}.union();
}

pub part DisplayRail() {
    y_offset=0.87mm;
    {_DisplayRailHousing() - Display() - _DisplaySpacer(DISPLAY_FRAME_HEIGHT).translate(y=y_offset)}.align(Z).union();
}

pub part HomeButton() {
    radius = 4.00mm;
    depth = WALL_THICKNESS / 2;
    {Circle(radius + 0.6mm).extrude(depth);Circle(radius).extrude(depth);}.align(Z).union();
}

pub part _CaseFront() {
    width = OUTER_WIDTH;
    height = OUTER_HEIGHT;
    plate = Rect(width, height).extrude(WALL_THICKNESS);

    // display_hole_height = DISPLAY_INSET + DISPLAY_HOLE_HEIGHT;
    // home_button_area_height = INNER_HEIGHT - display_hole_height;
    // y_offset = - INNER_HEIGHT / 2 + (home_button_area_height / 2);
    // home_button = HomeButton().reflect(Z).align(Z).translate(y=y_offset);

    plate; //  - home_button;
}

pub part _CaseWalls() {
    width = OUTER_WIDTH;
    height = OUTER_HEIGHT;
    Frame(width, height, WALL_THICKNESS)
            .extrude(CASE_DEPTH);
}

pub part _CaseFrame() {
    {  _CaseFront();  _CaseWalls();}.align(Z).union();
}


pub part _CaseFrame_TopCoverRails() {
    y_offset = -RAIL_THICKNESS / 2;
    _CaseFrame() - BackCover().translate(y=y_offset);
}

pub part _CaseFrame_AllRails() {
    y_offset = INNER_HEIGHT / 2 - DISPLAY_RAIL_HEIGHT / 2;
    z_offset = WALL_THICKNESS;
    {  _CaseFrame_TopCoverRails(); DisplayRail().translate(y=y_offset,z=z_offset);}.union();
}

pub part _DisplayWindow() {
    width = DISPLAY_HOLE_WIDTH;
    height = DISPLAY_HOLE_HEIGHT;
    depth = WALL_THICKNESS;
    Rect(width, height).extrude(depth);
}

pub part _CaseFrame_AllRails_DisplayWindow() {
    y_offset = INNER_HEIGHT / 2 - DISPLAY_HOLE_HEIGHT / 2 - DISPLAY_INSET;
    _CaseFrame_AllRails() - _DisplayWindow().translate(y=y_offset);
}


pub part _LicheePcbShim() {
    width = LICHEE_PCB_WIDTH;
    height = LICHEE_PCB_HEIGHT;
    depth = PCB_THICKNESS;
    Rect(width, height).extrude(depth).translate(x=0mm, y=0mm, z=0mm);
}

pub part _LicheeMicroSdShim() {
    // sd slot is not centered, just make it bigger than 11.10mm;
    width = MICRO_SD_WIDTH;
    height = MICRO_SD_HEIGHT;
    depth = MICRO_SD_DEPTH;
    Rect(width, height).extrude(depth);
}

pub part UsbCPort() {
    border_width = 0.6mm;
    width = USB_C_WIDTH;
    height = USB_C_HEIGHT;
    depth = USB_C_DEPTH;
    RoundedRect(width, height, radius = border_width).extrude(depth).rotate(x=90°);
}


pub part _LicheeCamConnector() {
    // steg
    // außen bis usbc: 15.41mm
    // tiefe: 2mm
    // breite: 16.7mm
    // height: 4.32mm from board

    width = 15.41mm;
    height = 4.32mm;
    depth = 2mm;


    Rect(width, height).extrude(depth);


}

pub part LicheeShim() {

    half_pcb_height = LICHEE_PCB_HEIGHT / 2;
    inset = 1mm;
    port_offset = half_pcb_height + inset + 0.25mm; // 0.25mm extra to keep the microSD hidden in the case
    sd_offset = half_pcb_height - MICRO_SD_HEIGHT / 2 + inset;
    // z_offset = -PCB_THICKNESS - height / 2;
    {
        {
            UsbCPort().translate(y=port_offset);
            _LicheePcbShim();
            _LicheeMicroSdShim().translate(y=sd_offset);

        }.align(Z);

        // cam connector
        y_offset=half_pcb_height - LICHEE_CAM_CONNECT_INSET;
        z_offset=PCB_THICKNESS / 2;
        _LicheeCamConnector().rotate(x=90°).translate(y=y_offset,z=z_offset); // y board position
    }.union();
}

pub part LicheeShimPositioned() {
    x_offset= LICHEE_PCB_WIDTH / 2 - WALL_THICKNESS / 2;
    y_offset= -INNER_HEIGHT/2 + LICHEE_PCB_HEIGHT / 2 - WALL_THICKNESS / 2;
    pcb_wiggling_room = 2.5mm;
    z_offset =  -USB_C_HEIGHT + WALL_THICKNESS + DISPLAY_FULL_THICKNESS + pcb_wiggling_room;
    LicheeShim().reflect(Y).translate(x=x_offset, y=y_offset, z=z_offset);
}

pub part PushButton(button_height=PUSH_BUTTON_BTN_DEPTH) {
    width = PUSH_BUTTON_WIDTH;
    height = PUSH_BUTTON_HEIGHT;
    depth = PUSH_BUTTON_DEPTH;

    button_radius = PUSH_BUTTON_RADIUS;

    footer = Rect(width, height).extrude(depth);
    button = Circle(button_radius).extrude(button_height);
    {footer;button;}.align(Z).union();
}

pub part ActionButton(pin_depth=0mm, pin_radius=PUSH_BUTTON_RADIUS - 0.25mm) {
    radius = ACTION_BUTTON_DIAMETER / 2;
    // depth = WALL_THICKNESS / 2;

    holder = Circle(ACTION_BUTTON_BASE_DIAMETER / 2).extrude(ACTION_BUTTON_BASE_DEPTH);
    button = Circle(radius).extrude(ACTION_BUTTON_BUTTON_DEPTH);

    push_button_pin = Circle(pin_radius).extrude(pin_depth);
    {push_button_pin;holder;button}.align(Z).union();
}

pub part ActionButtonRotated() {
    ActionButton().rotate(x=90°, y=-90°).align(Z);
}

pub part _PushButtonHolderRail(total_height=15mm) {

    width = PUSH_BUTTON_WIDTH + 1mm + 1mm;
    height = total_height;
    depth = 0.5mm;
    Rect(width, height).extrude(depth);
}
pub part PushButtonHolder(total_height=15mm, z_offset_extra=0mm,cable_rail_height=0mm) {
    rail = _PushButtonHolderRail(total_height=total_height);

    pb_wall_thickness = 1mm;
    width = PUSH_BUTTON_WIDTH - 0.3mm;
    height = total_height; // PUSH_BUTTON_HEIGHT + pb_wall_thickness;
    depth = PUSH_BUTTON_DEPTH + pb_wall_thickness;
    z_offset = pb_wall_thickness / 2 + z_offset_extra;
    holder = Rect(width, height).extrude(depth) - PushButtonHolderCableRail(push_button_total_height=total_height, rail_height=cable_rail_height);
    {rail;holder}.align(Z).union().reflect(Z).align(Z) - PushButton(button_height=10mm).translate(z=z_offset);
}

pub part PushButtonHolderSpacer(total_height=15mm, z_offset_extra=0mm) {
    pin_depth=ACTION_BUTTON_PIN_DEPTH; // PUSH_BUTTON_BTN_DEPTH;
    pin_radius=ACTION_BUTTON_BASE_DIAMETER/2; // +0.1mm;
    {PushButtonHolder(total_height, z_offset_extra);ActionButton(pin_depth=pin_depth, pin_radius=pin_radius);}.align(Z).union();
}


pub part PushButtonHolderSpacerRotated(z_offset_extra=20mm) {
    height = ACTION_BUTTON_RAIL_HEIGHT;
    x_offset = -INNER_WIDTH / 2 - ACTION_BUTTON_DEPTH; // todo: add action button height
    z_offset = OUTER_DEPTH - height - WALL_THICKNESS;
    PushButtonHolderSpacer(height, z_offset_extra)
    .rotate(x=90°, y=-90°)
    .align(Z).align(X).translate(x=x_offset, z=z_offset);
}



pub part ActionButtonRow(z_offset_extra=20mm) {
    zero_offset = INNER_HEIGHT / 2;

    power_offset = zero_offset - 5mm;
    vol_up_offset = zero_offset - 20mm;
    play_offset =  vol_up_offset - 10mm;
    vol_down_offset =  play_offset - 10mm;
    {
        PushButtonHolderSpacerRotated(z_offset_extra).translate(y=power_offset);
        PushButtonHolderSpacerRotated(z_offset_extra).translate(y=vol_up_offset);
        PushButtonHolderSpacerRotated(z_offset_extra).translate(y=play_offset);
        PushButtonHolderSpacerRotated(z_offset_extra).translate(y=vol_down_offset);

    }.union();
}

pub part ActionButtonRowRails() {
    width = 1mm + ACTION_BUTTON_PIN_DEPTH;
    height = DISPLAY_GLASS_HEIGHT; // INNER_HEIGHT / 2;
    depth = OUTER_DEPTH - 2*WALL_THICKNESS - DISPLAY_FULL_THICKNESS;

    x_offset = -INNER_WIDTH / 2;
    y_offset =  INNER_HEIGHT / 2 - DISPLAY_GLASS_HEIGHT;
    z_offset = WALL_THICKNESS + DISPLAY_FULL_THICKNESS;
    Rect(width, height).extrude(depth).align(X).align(Y).translate(x=x_offset, y=y_offset, z=z_offset);
}

pub part PrintVersionCase() {
    _CaseFrame_AllRails_DisplayWindow_LicheeHoles();
}

pub part PrintVersionBackCover() {
    BackCover().reflect(Z).align(Z).translate(x=OUTER_WIDTH + 20mm);
}

pub part PrintVersionHomeButton() {
    HomeButton().translate(x=-OUTER_WIDTH + 5mm );
}

pub part PrintVersionActionButton() {
    // z_offset=ACTION_BUTTON_DEPTH + PUSH_BUTTON_BTN_DEPTH;
    ActionButton(pin_depth=ACTION_BUTTON_PIN_DEPTH)
        .reflect(Z)
        .align(Z)
        .translate(x=-OUTER_WIDTH, y=-8mm);
}

pub part PrintVersionPushButtonHolder() {
    rotation=90°; //66°;
    PushButtonHolder(total_height=ACTION_BUTTON_RAIL_HEIGHT,z_offset_extra=0mm, cable_rail_height=0.5mm)
    .rotate(y=rotation)
    .align(Z)
    .translate(x=-OUTER_WIDTH, y=8mm);
}


pub part _CaseFrame_AllRails_DisplayWindow_LicheeHoles() {
    {_CaseFrame_AllRails_DisplayWindow();ActionButtonRowRails();_BottomPartHolderBlockPositioned();}.union() - LicheeShimPositioned() - ActionButtonRow() - AntennaShimPositioned() -Tp4057ShimPositioned() - Max17043ShimPositioned();
}

pub part PushButtonHolderCableRail(push_button_total_height=15mm, rail_height=1mm) {
    total_height=push_button_total_height;
    width = PUSH_BUTTON_WIDTH;
    height = rail_height;
    depth = PUSH_BUTTON_DEPTH+0.5mm;
    y_offset=total_height / 2 - height/2;
    z_offset=0mm;
    Rect(width, height).extrude(depth).translate(y=y_offset,z=z_offset);
}












// 16 x 12
// holes in 2.6mm
// usb stand out: 1.3mm
// total thickness: 4.4mm

pub part _Tp4057PcbShimHole() {
    radius = 0.75mm;
    depth = PCB_THICKNESS;
    Circle(radius).extrude(depth)
}

pub part _Tp4057PcbShim() {
    width = TP4057_PCB_WIDTH;
    height = TP4057_PCB_HEIGHT;
    depth = PCB_THICKNESS;
    x1_offset = TP4057_PCB_WIDTH / 2;
    x2_offset = -x1_offset;
    y_offset = TP4057_PCB_HEIGHT / 2 - 2.6mm;
    Rect(width, height).extrude(depth) - _Tp4057PcbShimHole().translate(x=x1_offset,y=y_offset) - _Tp4057PcbShimHole().translate(x=x2_offset,y=y_offset);
}

pub part Tp4057Shim() {
    half_pcb_height = TP4057_PCB_HEIGHT / 2;
    inset = 1.3mm;
    port_offset = half_pcb_height + inset;
    {UsbCPort().translate(y=port_offset);_Tp4057PcbShim();}.align(Z).union();
}

pub part Tp4057ShimPositioned() {
    x_offset=-INNER_WIDTH / 2 + (TP4057_PCB_WIDTH / 2) - WALL_THICKNESS/2; // build into the wall
    y_offset=-INNER_HEIGHT / 2 + (TP4057_PCB_HEIGHT / 2);
    z_offset=WALL_THICKNESS + PCB_THICKNESS;
    Tp4057Shim().rotate(x=180°).align(Z).translate(x=x_offset, y=y_offset, z=z_offset);
}




pub part _Max17043PcbShim() {
    width = MAX17043_PCB_WIDTH;
    height = MAX17043_PCB_HEIGHT;
    depth = MAX17043_PCB_THICKNESS;
    Rect(width, height).extrude(depth);
}

pub part Jst20Port() {
// Max17043 JST2.0
// 8.12 width
// 6.08 depth
// 7.15 height - 1.6mm (pcb thickness)

    width = 8.12mm;
    height = 5.56mm;
    depth = 6.08mm;
    Rect(width, height).extrude(depth).rotate(x=90°);
}

pub part Max17043Shim() {
    half_pcb_height = MAX17043_PCB_HEIGHT / 2;
    port_offset = half_pcb_height; // 0.25mm extra to keep the microSD hidden in the case
    {Jst20Port().translate(y=port_offset);_Max17043PcbShim();}.align(Z).union();
}

pub part AntennaShim() {
    // antenna
    // 14.2mm x 31.63mm (1mm pcb thickness)
    width = ANTENNA_WIDTH;
    height = ANTENNA_HEIGHT;
    depth = PCB_THICKNESS * 2;
    Rect(width, height).extrude(depth);
}

pub part AntennaShimPositioned() {
    y_offset=-INNER_HEIGHT / 2 + BOTTOM_PART_HOLDER_HEIGHT / 2;
    x_offset=-INNER_WIDTH / 2 + (ANTENNA_HEIGHT / 2);
    z_offset=WALL_THICKNESS;

    AntennaShim().rotate(90°).translate(x=x_offset, y=y_offset, z=z_offset);
}


pub part Max17043ShimPositioned() {
    x_offset=-INNER_WIDTH / 2 + (MAX17043_PCB_WIDTH / 2) +10mm;
    // y_offset=-INNER_HEIGHT / 2 + (MAX17043_PCB_HEIGHT / 2);
    inset = 0.87mm;
    y_offset=-INNER_HEIGHT / 2 + (MAX17043_PCB_HEIGHT / 2) + BOTTOM_PART_HOLDER_HEIGHT - MAX17043_PCB_HEIGHT + inset;
    z_offset=WALL_THICKNESS + BOTTOM_PART_HOLDER_THICKNESS;
    Max17043Shim().rotate(x=180°, z=180°).align(Z).translate(x=x_offset, y=y_offset, z=z_offset);
}


pub part _BottomPartHolderBlock() {
    width = BOTTOM_PART_HOLDER_WIDTH;
    height = BOTTOM_PART_HOLDER_HEIGHT;
    depth = PCB_THICKNESS * 2;
    Rect(width, height).extrude(depth);
}

pub part _BottomPartHolderBlockPositioned() {
    x_offset=-INNER_WIDTH/2 + BOTTOM_PART_HOLDER_WIDTH / 2;
    y_offset=-INNER_HEIGHT/2 + BOTTOM_PART_HOLDER_HEIGHT / 2;
    z_offset=WALL_THICKNESS;
    _BottomPartHolderBlock().translate(x=x_offset,y=y_offset,z=z_offset);
}

/*
pub part BottomPartHolder() {
    _BottomPartHolderBlockPositioned() - Tp4057ShimPositioned() - AntennaShimPositioned();
}
*/



// tp4057
// 12 x 6 (0.95pcb thickness)

// LicheeShim();

// BottomPartHolder();

// Max17043ShimPositioned();

// Tp4057ShimPositioned();
// LicheeShimPositioned();


#[export = "player-case.stl"]
PrintVersionCase();

#[export = "player-backcover.stl"]
PrintVersionBackCover();


#[export = "player-action-button.stl"]
PrintVersionActionButton();

#[export = "player-action-button-holder.stl"]
PrintVersionPushButtonHolder();
