use std::geo2d::*;
use std::ops::*;
use std::math::*;

pub const WALL_THICKNESS = 1.25mm;
pub const RAIL_THICKNESS = 0.6mm;

pub const OUTER_DEPTH = 11.60mm;
pub const OUTER_WIDTH = 45.00mm;
pub const OUTER_HEIGHT = 88.75mm;

pub const CASE_HEIGHT = OUTER_HEIGHT - WALL_THICKNESS;
pub const CASE_DEPTH = OUTER_DEPTH - WALL_THICKNESS;

pub const INNER_DEPTH = OUTER_DEPTH - 2 * WALL_THICKNESS;
pub const INNER_WIDTH = OUTER_WIDTH - 2 * WALL_THICKNESS;
pub const INNER_HEIGHT = OUTER_HEIGHT - 2 * WALL_THICKNESS;

pub const DISPLAY_HOLE_WIDTH = 32.02mm + 1.98mm;
pub const DISPLAY_HOLE_HEIGHT = 48.02mm + 1.98mm;

pub const DISPLAY_GLASS_WIDTH = 38.34mm;
pub const DISPLAY_GLASS_HEIGHT = 56.37mm;
pub const DISPLAY_GLASS_THICKNESS = 1.36mm;

pub const DISPLAY_FRAME_WIDTH = 36.15mm;
pub const DISPLAY_FRAME_HEIGHT = 55.88mm;
pub const DISPLAY_FRAME_THICKNESS = 2.00mm;

pub const DISPLAY_RAIL_HEIGHT = DISPLAY_GLASS_HEIGHT + WALL_THICKNESS;

pub const DISPLAY_FULL_THICKNESS = DISPLAY_GLASS_THICKNESS + DISPLAY_FRAME_THICKNESS;

pub const DISPLAY_INSET = (DISPLAY_GLASS_HEIGHT - DISPLAY_HOLE_HEIGHT) / 2;

pub const LICHEE_PCB_WIDTH=22.90mm;
pub const LICHEE_PCB_HEIGHT=35.60mm;
pub const LICHEE_PCB_DEPTH=1.00mm;

pub const MICRO_SD_WIDTH=14.00mm; // this technically is not correct (increased to make a bigger hole because the microSD slot is not centered)
pub const MICRO_SD_HEIGHT=16.00mm;
pub const MICRO_SD_DEPTH=1.50mm;

pub const USB_C_WIDTH=8.4mm;
pub const USB_C_HEIGHT=2.6mm;
pub const USB_C_DEPTH=7.5mm;


pub const PUSH_BUTTON_WIDTH = 6.15mm; // 6.10mm real width
pub const PUSH_BUTTON_HEIGHT = 3.95mm; // 3.91mm real height
pub const PUSH_BUTTON_DEPTH = 1.65mm; // 1.60mm real depth
pub const PUSH_BUTTON_DEPTH_KNOB = 2.25mm; // 2.18 real depth

pub const PUSH_BUTTON_RADIUS = 0.95mm; // 0.90mm real radius
pub const PUSH_BUTTON_BTN_DEPTH = 0.85mm; // 0.80mm real depth




pub part _DisplayGlass(height=DISPLAY_GLASS_HEIGHT) {
    width = DISPLAY_GLASS_WIDTH;
    depth = DISPLAY_GLASS_THICKNESS;
    Rect(width, height).extrude(depth);
}

pub part _DisplayFrame(height=DISPLAY_FRAME_HEIGHT) {
    width = DISPLAY_FRAME_WIDTH;
    depth = DISPLAY_FRAME_THICKNESS;
    Rect(width, height).extrude(depth);
}

pub part _DisplaySpacer(height=1mm) {
    {_DisplayGlass(height);_DisplayFrame(height);}.align(Z).union();
}

pub part Display() {
    {_DisplayGlass();_DisplayFrame();}.align(Z).union();
}

pub part ActionButton() {
    radius = 2.0mm;
    depth = WALL_THICKNESS / 2;

    holder = Circle(radius + 0.6mm).extrude(depth);
    button = Circle(radius).extrude(depth+1.5mm);

    {holder;button}.align(Z).union();
}

pub part ActionButtonPositioned() {
    x_offset=-INNER_WIDTH / 2;
    z_offset=INNER_DEPTH / 2 + DISPLAY_FULL_THICKNESS / 2 + 1mm;

    ActionButton().rotate(x=90°, y=-90°).translate(x=x_offset, z=z_offset);
}


pub part ActionButtonRow() {
    top_offset = INNER_HEIGHT / 2 - WALL_THICKNESS / 2;

    power_offset = top_offset - 10mm;
    ActionButtonPositioned().translate(y=power_offset);

    vol_up_offset = power_offset - 15mm;
    ActionButtonPositioned().translate(y=vol_up_offset);

    play_offset = vol_up_offset - 12mm;
    ActionButtonPositioned().translate(y=play_offset);

    vol_down_offset = play_offset - 12mm;
    ActionButtonPositioned().translate(y=vol_down_offset);
}

pub part _BackCoverRail() {
    width = INNER_WIDTH + RAIL_THICKNESS * 2;
    height = INNER_HEIGHT + RAIL_THICKNESS;
    depth = RAIL_THICKNESS;
    y_offset=RAIL_THICKNESS/2;
    Rect(width, height).extrude(depth);
}

pub part _BackCoverFiller() {
    width = INNER_WIDTH;
    height = INNER_HEIGHT;
    depth = WALL_THICKNESS - RAIL_THICKNESS;
    y_offset = RAIL_THICKNESS / 2;
    Rect(width, height).extrude(depth).translate(x=0mm, y=y_offset, z=0mm);
}

pub part _BackCoverBack() {
    {_BackCoverRail();_BackCoverFiller();}.align(Z).union();
}

pub part _BackCoverTop() {
    width = OUTER_WIDTH;
    height = WALL_THICKNESS;
    depth = OUTER_DEPTH;
    y_offset = CASE_HEIGHT/2 + RAIL_THICKNESS / 2;
    Rect(width, height).extrude(depth).translate(y=y_offset);
}

pub part BackCover() {
    z_offset = CASE_DEPTH;
    {_BackCoverTop();_BackCoverBack().translate(z=z_offset)}.union();
}

pub part LicheeCenterSupport() {
    width=2mm;
    height=3mm;
    depth = INNER_DEPTH;
    Rect(width, height).extrude(depth);
}

pub part _DisplayRailHousing() {
    width = INNER_WIDTH;
    height = DISPLAY_RAIL_HEIGHT;
    depth = DISPLAY_FULL_THICKNESS;

    lsupp = LicheeCenterSupport().translate(y=-29.4mm, x=-1mm);
    {Rect(width, height).extrude(depth); lsupp}.union();
}

pub part DisplayRail() {
    y_offset=0.87mm;
    {_DisplayRailHousing() - Display() - _DisplaySpacer(DISPLAY_FRAME_HEIGHT).translate(y=y_offset)}.align(Z).union();
}

pub part HomeButton() {
    radius = 5.00mm;
    depth = WALL_THICKNESS / 2;
    {Circle(radius + 0.6mm).extrude(depth);Circle(radius).extrude(depth);}.align(Z).union();
}

pub part _CaseFront() {
    width = OUTER_WIDTH;
    height = OUTER_HEIGHT;
    plate = Rect(width, height).extrude(WALL_THICKNESS);
    display_hole_height = DISPLAY_INSET + DISPLAY_HOLE_HEIGHT;
    home_button_area_height = INNER_HEIGHT - display_hole_height;

    y_offset = - INNER_HEIGHT / 2 + (home_button_area_height / 2);
    home_button = HomeButton().reflect(Z).align(Z).translate(y=y_offset);

    plate - home_button;
}

pub part _CaseWalls() {
    width = OUTER_WIDTH;
    height = OUTER_HEIGHT;
    Frame(width, height, WALL_THICKNESS)
            .extrude(CASE_DEPTH);
}

pub part _CaseFrame() {
    {  _CaseFront();  _CaseWalls();}.align(Z).union();
}


pub part _CaseFrame_TopCoverRails() {
    y_offset = -RAIL_THICKNESS / 2;
    _CaseFrame() - BackCover().translate(y=y_offset);
}

pub part _CaseFrame_AllRails() {
    y_offset = INNER_HEIGHT / 2 - DISPLAY_RAIL_HEIGHT / 2;
    z_offset = WALL_THICKNESS;
    {  _CaseFrame_TopCoverRails(); DisplayRail().translate(y=y_offset,z=z_offset);}.union();
}

pub part _DisplayWindow() {
    width = DISPLAY_HOLE_WIDTH;
    height = DISPLAY_HOLE_HEIGHT;
    depth = WALL_THICKNESS;
    Rect(width, height).extrude(depth);
}

pub part _CaseFrame_AllRails_DisplayWindow() {
    y_offset = INNER_HEIGHT / 2 - DISPLAY_HOLE_HEIGHT / 2 - DISPLAY_INSET;
    _CaseFrame_AllRails() - _DisplayWindow().translate(y=y_offset);
}


pub part _LicheePcbShim() {
    width = LICHEE_PCB_WIDTH;
    height = LICHEE_PCB_HEIGHT;
    depth = LICHEE_PCB_DEPTH;
    Rect(width, height).extrude(depth).translate(x=0mm, y=0mm, z=0mm);
}

pub part _LicheeMicroSdShim() {
    // sd slot is not centered, just make it bigger than 11.10mm;
    width = MICRO_SD_WIDTH;
    height = MICRO_SD_HEIGHT;
    depth = MICRO_SD_DEPTH;
    Rect(width, height).extrude(depth);
}

pub part UsbCPort() {
    border_width = 0.6mm;
    width = USB_C_WIDTH;
    height = USB_C_HEIGHT;
    depth = USB_C_DEPTH;
    RoundedRect(width, height, radius = border_width).extrude(depth).rotate(x=90°);
}


pub part LicheeShim() {
    half_pcb_height = LICHEE_PCB_HEIGHT / 2;
    inset = 1mm;
    port_offset = half_pcb_height + inset + 0.25mm; // 0.25mm extra to keep the microSD hidden in the case
    sd_offset = half_pcb_height - MICRO_SD_HEIGHT / 2 + inset;
    z_offset = -LICHEE_PCB_DEPTH - height / 2;
    {UsbCPort().translate(y=port_offset);_LicheePcbShim();_LicheeMicroSdShim().translate(y=sd_offset);}.align(Z).union();
}

pub part LicheeShimPositioned() {
    x_offset= LICHEE_PCB_WIDTH / 2 - WALL_THICKNESS / 2;
    y_offset= -INNER_HEIGHT/2 + LICHEE_PCB_HEIGHT / 2 - WALL_THICKNESS / 2;
    pcb_wiggling_room = 2.5mm;
    z_offset =  -USB_C_HEIGHT + WALL_THICKNESS + DISPLAY_FULL_THICKNESS + pcb_wiggling_room;
    LicheeShim().reflect(Y).translate(x=x_offset, y=y_offset, z=z_offset);
}
pub part _CaseFrame_AllRails_DisplayWindow_LicheeHoles() {
    _CaseFrame_AllRails_DisplayWindow() - LicheeShimPositioned() - ActionButtonRow();
}

pub part PushButton() {
    width = PUSH_BUTTON_WIDTH;
    height = PUSH_BUTTON_HEIGHT;
    depth = PUSH_BUTTON_DEPTH;

    button_radius = PUSH_BUTTON_RADIUS;
    button_height = PUSH_BUTTON_BTN_DEPTH;

    footer = Rect(width, height).extrude(depth);
    button = Circle(button_radius).extrude(button_height);
    {footer;button;}.align(Z).union();
}





pub part PrintVersionCase() {
    _CaseFrame_AllRails_DisplayWindow_LicheeHoles();
}

pub part PrintVersionBackCover() {
    BackCover().reflect(Z).align(Z).translate(x=OUTER_WIDTH + 20mm);
}

pub part PrintVersionHomeButton() {
    HomeButton().translate(x=-OUTER_WIDTH + 5mm );
}

pub part PrintVersionActionButton() {
    ActionButton().translate(x=-OUTER_WIDTH - 5mm);
}


pub part PushButtonHolder(total_height=0mm) {

    extra_space = 0.5mm;

    extra_height = total_height - PUSH_BUTTON_HEIGHT - extra_space;
    if extra_height < 0mm {
        extra_height = 0mm;
    }
    // push-button-width: 6.15, ActionButton-radius: 5.2mm
    width = 7.2mm; // action-button-radius + 2x1mm;
    height = PUSH_BUTTON_HEIGHT + extra_space + extra_height;
    depth = PUSH_BUTTON_DEPTH_KNOB + extra_space;
    z_offset = extra_space;

    holder = Rect(width, height).extrude(depth) - PushButton().translate(z=z_offset);

    // x = overstand
    x = 1mm;
    width = width + x;
    height = height + extra_space * 2 + 2*x;
    depth = depth - extra_space;
    frame = Frame(width, height, extra_space + x)
            .extrude(depth);
            // .translate(x=10mm);

    holder - frame;
}



pub part PushButtonHolderPositioned() {
    x_offset = -INNER_WIDTH / 2 + 2.9mm;

    // display_inset = (56.37mm -  (48.02mm + 1.98mm)) / 2 = 3.185
    y_offset = INNER_HEIGHT / 2 - 7.2mm / 2; // 39.61mm;
    z_offset = 7.20mm; //INNER_DEPTH / 2 + DISPLAY_FULL_THICKNESS / 2;
    PushButtonHolder(total_height=5.2mm).rotate(x=90°, y=-90°).translate(x=x_offset, y=y_offset,z=z_offset);
}

// PushButtonHolderPositioned();
y_offset = - (10mm - 2.6mm); // power - btn_radius
PushButtonHolderPositioned().translate(y=y_offset);

y_offset = y_offset - 15mm;
PushButtonHolderPositioned().translate(y=y_offset);

y_offset = y_offset - 12mm;
PushButtonHolderPositioned().translate(y=y_offset);

y_offset = y_offset - 12mm;
PushButtonHolderPositioned().translate(y=y_offset);

/*
// pb = PushButtonHolderPositioned();
// pb.translate(y=10mm);

y_offset = - (10 - 2.6)mm; // power - btn_radius
PushButtonHolderPositioned().translate(y=y_offset);


    power_offset = top_offset - 10mm;
    ActionButtonPositioned().translate(y=power_offset);

    vol_up_offset = power_offset - 15mm;
    ActionButtonPositioned().translate(y=vol_up_offset);

    play_offset = vol_up_offset - 12mm;
    ActionButtonPositioned().translate(y=play_offset);

    vol_down_offset = play_offset - 12mm;
    ActionButtonPositioned().translate(y=vol_down_offset);
*/



#[export = "player-case.stl"]
PrintVersionCase();
/*
#[export = "player-backcover.stl"]
PrintVersionBackCover();

#[export = "player-home-button.stl"]
PrintVersionHomeButton();

#[export = "player-action-button.stl"]
PrintVersionActionButton();
*/