use std::geo2d::*;
use std::ops::*;
use std::math::*;

// SMD-Buttons: 3.5 x 6.0 x 2.5mm (w, h, d)

// 4mm height camera stand
// 14.00mm from usb-c board end
// 3.5mm from sides
// 1.00mm overstand USB-C
// TP4057: 12.00mm
// 12.00mm (tp4057) + 23 (lichee) = 35
// 42.5 - 35 = 7.5mm
// USB-C is bottom, SD is top

// 17.50mm TP4057 length (incl USB-C)
// 23.00mm Lichee width
// 17.50 + 23.00 = 40.50mm vs 42.50mm
// TP4057 12.00mm x 17.50mm (incl USB-C)
// Gauge: 10.00mm x 24.00mm
// Lichee: 22.90mm x 35.60mm
pub const WALL_THICKNESS = 1.25mm;

pub const OUTER_DEPTH = 11.60mm;
pub const OUTER_WIDTH = 45.00mm;
pub const OUTER_HEIGHT = 88.75mm;

pub const CASE_HEIGHT = OUTER_HEIGHT - WALL_THICKNESS;

pub const INNER_DEPTH = OUTER_DEPTH - 2 * WALL_THICKNESS;
pub const INNER_WIDTH = OUTER_WIDTH - 2 * WALL_THICKNESS;
pub const INNER_HEIGHT = OUTER_HEIGHT - 2 * WALL_THICKNESS;

// Glass: 38.34 x 56.37 x 1.36mm
// Frame: 36.15 x 55.88 x 2mm
// Visible Area: 32.02 x 48.02
pub const DISPLAY_HOLE_WIDTH = 32.02mm + 1.98mm;
pub const DISPLAY_HOLE_HEIGHT = 48.02mm + 1.98mm;

pub const DISPLAY_GLASS_WIDTH = 38.34mm;
pub const DISPLAY_GLASS_HEIGHT = 56.37mm;
pub const DISPLAY_GLASS_THICKNESS = 1.36mm;

pub const DISPLAY_FRAME_WIDTH = 36.15mm;
pub const DISPLAY_FRAME_HEIGHT = 55.88mm;
pub const DISPLAY_FRAME_THICKNESS = 2.00mm;
pub const DISPLAY_FULL_THICKNESS = DISPLAY_GLASS_THICKNESS + DISPLAY_FRAME_THICKNESS;

pub const LICHEE_PCB_WIDTH=22.90mm;
pub const LICHEE_PCB_HEIGHT=35.60mm;
pub const LICHEE_PCB_DEPTH=1.00mm;





pub part Case(rows = 2, columns = 4) {
    width = OUTER_WIDTH;
    height = CASE_HEIGHT;
    cap = Rect(width, height).extrude(WALL_THICKNESS);
    base = Frame(width, height, WALL_THICKNESS)
            .extrude(OUTER_DEPTH - WALL_THICKNESS);
    bottom_hole = BottomWallHole();

    {  cap;  base;}.align(Z).union() - bottom_hole;
}

pub part BottomWallHole() {
    width = INNER_WIDTH;
    height = WALL_THICKNESS;
    depth = OUTER_DEPTH - WALL_THICKNESS;
    y_offset = CASE_HEIGHT / 2  - WALL_THICKNESS / 2;
    z_offset = WALL_THICKNESS;
    Rect(width, height).extrude(depth).translate(x=0mm, y=y_offset, z=z_offset);
}

pub part DisplayHole() {
    width = DISPLAY_HOLE_WIDTH;
    height = DISPLAY_HOLE_HEIGHT;
    depth = WALL_THICKNESS;
    y_offset =  INNER_HEIGHT / 2 - DISPLAY_HOLE_HEIGHT / 2 - WALL_THICKNESS;
    Rect(width, height).extrude(depth).translate(x=0mm, y=y_offset, z=0mm);
}

pub part DisplayGlass() {
    width = DISPLAY_GLASS_WIDTH;
    height = DISPLAY_GLASS_HEIGHT;
    depth = DISPLAY_GLASS_THICKNESS;
    Rect(width, height).extrude(depth);
}

pub part DisplayFrame() {
    width = DISPLAY_FRAME_WIDTH;
    height = DISPLAY_FRAME_HEIGHT;
    depth = DISPLAY_FRAME_THICKNESS;
    Rect(width, height).extrude(depth);
}

pub part Display() {
    glass = DisplayGlass();
    frame = DisplayFrame();
    {glass;frame;}.align(Z).union();
}

pub part DisplayRailShaveBottom() {
    width = DISPLAY_FRAME_WIDTH;
    height = 20mm;
    depth = 5mm;
    y_offset = -10mm;
    z_offset = 0mm;
    Rect(width, height).extrude(depth).translate(x=0mm, y=y_offset, z=z_offset);
}



pub part DisplayRailHousing() {
    width = INNER_WIDTH;
    height = DISPLAY_GLASS_HEIGHT + WALL_THICKNESS;
    depth = DISPLAY_FULL_THICKNESS;
    display_rail_housing = Rect(width, height).extrude(depth);

    shave_offset = ( height / 2);
    shave_top = Rect(width, WALL_THICKNESS * 2).extrude(depth).translate(x=0mm, y=shave_offset, z=0mm);

    display_rail_housing - shave_top;
}

pub part TopCover() {
    rail_width = 0.6mm;
    rail_height = 0.6mm;
    width = INNER_WIDTH + rail_width * 2;
    height = INNER_HEIGHT + rail_width;
    depth = rail_height;
    y_offset=rail_height/2; //0.3mm;
    back_cover_rail = Rect(width, height).extrude(depth).translate(x=0mm, y=y_offset, z=0mm);

    width = INNER_WIDTH;
    height = INNER_HEIGHT;
    depth = WALL_THICKNESS;
    y_offset = rail_height;
    back_cover = Rect(width, height).extrude(depth).translate(x=0mm, y=y_offset, z=0mm);

    width = OUTER_WIDTH;
    height = WALL_THICKNESS;
    depth = OUTER_DEPTH;
    y_offset = CASE_HEIGHT/2 + rail_height;
    z_offset = -OUTER_DEPTH + WALL_THICKNESS;
    top_cover = Rect(width, height).extrude(depth).translate(x=0mm, y=y_offset, z=z_offset);


    {back_cover_rail;back_cover;top_cover;}.union();
    //
}

pub part LicheeCenterSupport() {
    width=2mm;
    height=10mm;
    depth = INNER_DEPTH;
    Rect(width, height).extrude(depth);
}


pub part DisplayRail() {
    // y_offset = -35mm;
    // center_support = LicheeCenterSupport().translate(y=y_offset);
    {DisplayRailHousing() - Display()}.union() - DisplayRailShaveBottom().translate(y=-15mm);
}


pub part CaseWithDisplayHole() {
    Case() - DisplayHole()
}

pub part CaseWithDisplayHoleAndRail() {
    y_offset = OUTER_HEIGHT / 2 - DISPLAY_GLASS_HEIGHT / 2;
    {CaseWithDisplayHole(); DisplayRail().translate(y=y_offset, z=WALL_THICKNESS)}.union();
}

pub part TopCoverHole() {
    TopCover().translate(y=0mm, z=INNER_DEPTH+WALL_THICKNESS + 0mm);
}


pub part TopCoverUpsideDown() {
    x_offset=OUTER_WIDTH + 20mm;
    TopCover().translate(x=x_offset).reflect(Z).align(Z);
}

pub part LicheePcbShim() {
    width = LICHEE_PCB_WIDTH;
    height = LICHEE_PCB_HEIGHT;
    depth = LICHEE_PCB_DEPTH;
    Rect(width, height).extrude(depth).translate(x=0mm, y=0mm, z=0mm);
}

pub part LicheeUsbShim() {
    border_width = 0.6mm;
    width = 8.4mm;
    height = 2.6mm;
    depth = 7.5mm;
    // Rect(width, height).extrude(depth).translate(x=0mm, y=0mm, z=0mm);
    y_offset = LICHEE_PCB_HEIGHT / 2 + 1mm;
    z_offset = LICHEE_PCB_DEPTH;
    RoundedRect(width, height, radius = border_width).extrude(depth).rotate(x=90°).align(Z).translate(x=0mm, y=y_offset, z=z_offset);
}

pub part LicheeMicroSdShim() {
    // width = 11.10mm;
    width = 14.00mm; // not centered, just make it bigger
    height = 1.50mm;
    depth = 16.00mm;
    y_offset = LICHEE_PCB_HEIGHT / 2 + 1mm;
    z_offset = -LICHEE_PCB_DEPTH - height / 2;
    Rect(width, height).extrude(depth).rotate(x=90°).align(Z).translate(x=0mm, y=y_offset, z=z_offset);
}

pub part LicheeShim() {
    LicheeUsbShim();
    LicheePcbShim();
    LicheeMicroSdShim();
}

pub part CaseWithDisplayAndTopCoverHoles() {
    CaseWithDisplayHoleAndRail() - TopCoverHole();
}

pub part HomeButton() {
    radius = 5.00mm;
    depth = WALL_THICKNESS / 2;
    Circle(radius).extrude(depth).translate(z=depth);
    Circle(radius + 2mm).extrude(depth);
}

pub part ActionButton() {
    // SMD-Buttons: 3.5 x 6.0 x 2.5mm (w, h, d)
    // press goes from 2.5mm to 2.3mm thickness
    radius = 2.0mm;
    depth = WALL_THICKNESS / 2;
    Circle(radius).extrude(depth+1.5mm).translate(z=depth);
    Circle(radius + 0.6mm).extrude(depth);
}

pub part ActionButtonPositioned() {
    x_offset=-INNER_WIDTH / 2;
    z_offset=INNER_DEPTH / 2 + DISPLAY_FULL_THICKNESS / 2 + 1mm;

    ActionButton().rotate(x=90°, y=-90°).translate(x=x_offset, z=z_offset);
}

pub part ActionButtonRow() {
    top_offset = INNER_HEIGHT / 2 - WALL_THICKNESS / 2;

    power_offset = top_offset - 5mm;
    ActionButtonPositioned().translate(y=power_offset);

    vol_up_offset = power_offset - 15mm;
    ActionButtonPositioned().translate(y=vol_up_offset);

    play_offset = vol_up_offset - 7mm;
    ActionButtonPositioned().translate(y=play_offset);

    vol_down_offset = play_offset - 7mm;
    ActionButtonPositioned().translate(y=vol_down_offset);
}




pub part CaseWithDisplay_TopCover_LicheeHoles() {
    h = INNER_HEIGHT / 2 - LICHEE_PCB_HEIGHT;

    x_offset = INNER_WIDTH / 2 - LICHEE_PCB_WIDTH / 2 + WALL_THICKNESS / 2;
    y_offset = - (LICHEE_PCB_HEIGHT / 2) - h; //0mm; // -(INNER_HEIGHT - LICHEE_PCB_HEIGHT);
    z_offset = WALL_THICKNESS + DISPLAY_FULL_THICKNESS + 2mm; // INNER_HEIGHT / 2;


    CaseWithDisplayAndTopCoverHoles() - LicheeShim().rotate(x=180°).translate(x=x_offset,y=y_offset,z=z_offset);
}

pub part CaseWithDisplay_TopCover_Lichee_HomeButtonHoles() {

    x_offset = 0mm; // INNER_WIDTH / 2 - LICHEE_PCB_WIDTH / 2 + WALL_THICKNESS / 2;
    y_offset = -25mm; // - (LICHEE_PCB_HEIGHT / 2) - h; //0mm; // -(INNER_HEIGHT - LICHEE_PCB_HEIGHT);
    z_offset = 0mm; // + DISPLAY_FULL_THICKNESS + 2mm; // INNER_HEIGHT / 2;

    CaseWithDisplay_TopCover_LicheeHoles() - HomeButton().reflect(Z).align(Z).translate(x=x_offset,y=y_offset,z=z_offset);
}


pub part CaseWithDisplay_TopCover_Lichee_HomeButton_ActionButtonHoles() {

    CaseWithDisplay_TopCover_Lichee_HomeButtonHoles() - ActionButtonRow();
}


// y_offset=DISPLAY_INNER_HEIGHT/2;
// {Case();DisplayRail().translate(y=-15.6mm, z=WALL_THICKNESS)}.union() - DisplayHole();
// DisplayRailHousing() - Display();
// DisplayRail();
// DisplayRail().translate(y=15.6mm, z=WALL_THICKNESS);

// TopCover().rotate(180°);

// LicheeShim();
// HomeButton();
// ActionButton();

#[export = "player-case.stl"]
CaseWithDisplay_TopCover_Lichee_HomeButton_ActionButtonHoles();

#[export = "player-backcover.stl"]
TopCoverUpsideDown();

