// solving lists without gridlayout supporting it: https://github.com/slint-ui/slint/discussions/5422
// sample slint programs:
// - https://github.com/Vadoola/Tomotroid
// - https://github.com/slint-ui/slint/tree/master/demos/home-automation

import {
    Button,
    ListView,
    HorizontalBox,
    Palette,
    ScrollView,
    Slider,
    Switch,
    VerticalBox,
} from "std-widgets.slint";

import {SlintAudioPlayer, SlintMediaSource, SlintMediaSourceItem} from "../globals.slint";
import { PiListItem } from "../_components/PiListItem.slint";

export component Audiobooks {
    // in-out property <[SlintMediaSourceItem]> items; // Accepts a model of strings

    init => {
        SlintMediaSource.query(2);
    }

    VerticalBox {
        padding:0px;
        padding-left:15px;


/*
        Rectangle {
            border-color:black;
            border-width:1px;
            width:100%;
            height:50px;
            background: red;
        }
*/
        ScrollView {
            for item in SlintMediaSource.query-results:
                PiListItem {
                    height:80px;
                    title: item.name;
                    subtitle: item.series + " " + item.part;
                    description: item.artist;
                    has-icon: item.has-cover;
                    icon: item.thumbnail;

                    clicked => {
                        SlintAudioPlayer.play_media(item.id);
                    }
                }


        }

    }
}