// solving lists without gridlayout supporting it: https://github.com/slint-ui/slint/discussions/5422
// sample slint programs:
// - https://github.com/Vadoola/Tomotroid
// - https://github.com/slint-ui/slint/tree/master/demos/home-automation

import {
    Button,
    ListView,
    HorizontalBox,
    Palette,
    ScrollView,
    Slider,
    Switch,
    VerticalBox,
} from "std-widgets.slint";

import {SlintNavigation, SlintAudioPlayer, SlintMediaSource, SlintMediaSourceItem} from "../globals.slint";

export component Details {
    in-out property <string> item-id;
    in-out property <SlintMediaSourceItem> item;

    init => {
        SlintMediaSource.find(item-id);
    }

    if SlintMediaSource.find-results.length == 0: Text {
        text: "No items";
    }
    for item in SlintMediaSource.find-results: VerticalBox {
        Image {
            source: item.cover;
        }
        Text {
            text: "ChapterCount: " + item.chapters.length;
        }
        Text {
            text: item.id;
        }
        Text {
            text: item.name;
        }

        Text {
            text: item.genre;
        }

        Button {
            text: "Play";
            clicked => {
                SlintAudioPlayer.play_media(item.id);
            }
        }
    }
}