import { Button, VerticalBox, ScrollView, HorizontalBox } from "std-widgets.slint";
import { MainMenuButton } from "./home/main_menu_button.slint";

export global Icons {
    in-out property<image> audiobooks: @image-url("../images/icons/audiobooks.svg");
    in-out property<image> music: @image-url("../images/icons/music.svg");
    in-out property<image> search: @image-url("../images/icons/search.svg");
    in-out property<image> settings: @image-url("../images/icons/settings.svg");
}

export component Home {
    callback navigateTo(string);

    VerticalBox {
            alignment: start;
            HorizontalBox {
                alignment: center;
                MainMenuButton {
                    image: Icons.audiobooks;
                    text: "Books";
                    clicked() => {
                        navigateTo("books");
                    }
                }

                MainMenuButton {
                    image: Icons.music;
                    text: "Music";
                }
            }

            HorizontalBox {
                alignment: center;
                MainMenuButton {
                    image: Icons.search;
                    text: "Search";
                }
                MainMenuButton {
                    image: Icons.settings;
                    text: "Settings";
                }
            }

        }
}


// component