import {
    HorizontalBox,
    Palette,
    Slider,
    Switch,
    VerticalBox,
} from "std-widgets.slint";

export component Settings {
    VerticalBox {
        alignment: start;
        VerticalBox {
            Text {
                text: "Brightness";
            }

            Slider {
                value: 0;
                minimum: 0;
                maximum: 2000;

                // changed(value) => {}
            }
        }

        Switch {
            horizontal-stretch: 0;
            text: @tr("Dark Mode");
            checked: Palette.color-scheme == ColorScheme.dark;
            toggled => {
                Palette.color-scheme = self.checked ? ColorScheme.dark : ColorScheme.light;
            }
        }
    }
}
