import {
    HorizontalBox,
    Palette,
    Slider,
    Switch,
    VerticalBox, Button,
} from "std-widgets.slint";


import {SlintPreferences, SlintAudioPlayer} from "../globals.slint";

export component Settings {
    VerticalBox {
        alignment: start;
        VerticalBox {
            Text {
                text: "Brightness";
            }

            Slider {
                value <=> SlintPreferences.brightness;
                step: 0.01;
                minimum: 0.01;
                maximum: 1;
                changed value => {
                    SlintPreferences.sync();
                }
            }
        }
        VerticalBox {
            Switch {
                horizontal-stretch: 0;
                text: @tr("Dark Mode");
                checked: Palette.color-scheme == ColorScheme.dark;
                toggled => {
                    Palette.color-scheme = self.checked ? ColorScheme.dark : ColorScheme.light;
                    SlintPreferences.color-scheme = Palette.color-scheme;
                    SlintPreferences.sync();
                }
            }
        }

        VerticalBox {
            Button {
                text: "Play test audio";
                clicked => {
                    SlintAudioPlayer.play("preftest");
                }

            }

        }


    }
}
