export global SlintIcons {
    in-out property <image> audiobooks: @image-url("images/icons/audiobooks.png");
    in-out property <image> music: @image-url("images/icons/music.png");
    in-out property <image> search: @image-url("images/icons/search.png");
    in-out property <image> settings: @image-url("images/icons/settings.png");
}

export global SlintAudioPlayer {
    callback play_test();
    callback play_media(string);
    callback play();
    callback pause();
}

export global SlintNavigation {
    in-out property <[string]> route: ["home"];
    in-out property <int> history_index: 0;
    in-out property <[[string]]> history: [["home"]];

    callback goto([string]);
    callback back();
    callback forward();
}

export global SlintPreferences {
    callback sync();

    in-out property <ColorScheme> color-scheme: ColorScheme.dark;
    // in-out property <bool> fullscreen: false;
    in-out property <float> brightness: 0.3;
}



export struct SlintMediaSourceItem {
    id: string,
    media_type: int,
    name: string,
    genre: string,
    artist: string,
    album: string,
    composer: string,
    series: string,
    part: string,
    // cover: string,
    // thumbnail: string

    has-cover: bool,
    cover: image,
    thumbnail: image

}

export global SlintMediaSource {
    in-out property <bool> is-loading;
    in-out property <[SlintMediaSourceItem]> query-results;
    // in-out property <SlintMediaSourceItem> find-by-id-result;

    callback query(mediaType: int);
    callback findById(id: string);

}