import { SlintIcons } from "globals.slint";

import {
    HorizontalBox,
    VerticalBox,
} from "std-widgets.slint";

import { HomeButton } from "home/home_button.slint";

export component Home {
    VerticalBox {
        alignment: start;
        HorizontalBox {
            alignment: center;
            HomeButton {
                image: SlintIcons.audiobooks;
                route: ["audiobooks"];
                text: "Audio books";
            }

            HomeButton {
                image: SlintIcons.music;
                route: ["music"];
                text: "Music";
            }
        }

        HorizontalBox {
            alignment: center;
            HomeButton {
                image: SlintIcons.search;
                route: ["search"];
                text: "Search";
            }

            HomeButton {
                image: SlintIcons.settings;
                route: ["settings"];
                text: "Settings";
            }
        }
    }
}
