import { SlintAudioPlayer, SlintIcons, SlintNavigation, SlintPreferences } from "globals.slint";

export { SlintAudioPlayer, SlintNavigation, SlintPreferences }

import {
    Button,
    HorizontalBox,
    ListView,
    Palette,
    ScrollView,
    Slider,
    Switch,
    VerticalBox,
} from "std-widgets.slint";
import { Navigator } from "navigator.slint";

import { Home } from "home.slint";
import { Audiobooks } from "main/audiobooks.slint";
import { Music } from "main/music.slint";
import { Search } from "main/search.slint";
import { Settings } from "main/settings.slint";

export component MainWindow inherits Window {
    in property <[string]> files; // Accepts a model of strings

    default-font-family: "Lato";
    default-font-size: 16pt;

    in-out property <physical-length> swipe-area-width: 50px;

    // 368 x 552
    preferred-width: 368px;
    preferred-height: 552px;

    init => {
        // load preferences
        // restore route
        Palette.color-scheme = SlintPreferences.color-scheme;

    }

    TouchArea {
        x: 0;
        y: 0;
        width: swipe-area-width;
        height: 100%;
        double-clicked => {
            SlintNavigation.back();
        }
    }


    VerticalBox {
        padding: 0;
        ScrollView {
            ListView {
                for file_name in files : Text {
                    text: file_name;
                }
            }

            if SlintNavigation.route[0] == "home": Home { }
            if SlintNavigation.route[0] == "audiobooks": Audiobooks { }
            if SlintNavigation.route[0] == "music": Music { }
            if SlintNavigation.route[0] == "settings": Settings { }
            if SlintNavigation.route[0] == "search": Search { }
        }
    }
    TouchArea {
        x: root.width - swipe-area-width;
        y: 0;
        width: swipe-area-width;
        height: 100%;
        double-clicked => {
            SlintNavigation.forward();
        }
    }
}
