// SlintCallbacks
import { SlintAudioPlayer, SlintMediaSource, SlintIcons, SlintNavigation, SlintPreferences } from "globals.slint";

export { SlintAudioPlayer, SlintMediaSource, SlintNavigation, SlintPreferences }

import {
    Button,
    HorizontalBox,
    ListView,
    Palette,
    ScrollView,
    Slider,
    Switch,
    VerticalBox,
} from "std-widgets.slint";
import { Navigator } from "navigator.slint";

import { Home } from "home.slint";
import { Audiobooks } from "main/audiobooks.slint";
import { Music } from "main/music.slint";
import { Search } from "main/search.slint";
import { Settings } from "main/settings.slint";
import { Details } from "main/details.slint";
import { Player } from "main/player.slint";


export component MainWindow inherits Window {
    default-font-family: "Lato";
    default-font-size: 16pt;


    in-out property <physical-length> swipe-area-width: 50px;

    in-out property <physical-length> cur-pos: 0px;
    in-out property <physical-length> pressed-pos: 0px;


    // 368 x 552
    width: 368px;
    height: 552px;

    init => {
        // load preferences
        // restore route
        Palette.color-scheme = SlintPreferences.color-scheme;

    }

    SwipeGestureHandler {
        x: 0;
        y: 0;
        width:368px;
        height:552px;
        handle-swipe-right: SlintPreferences.enable-gestures;
        handle-swipe-left: SlintPreferences.enable-gestures;
        swiped => {
            if (SlintPreferences.enable-gestures) {
                if (self.current-position.x > self.pressed-position.x) {
                    SlintNavigation.back()
                } else if (self.current-position.x < self.pressed-position.x) {
                    SlintNavigation.forward()
                }
            }
        }
    }

    Flickable {
    /*
        VerticalBox {
            for i in 100: Text {
                text: i;

            }
        }
        */

        VerticalBox {
            padding:0px;
            if SlintNavigation.route[0] == "home": Home { }
            if SlintNavigation.route[0] == "audiobooks": Audiobooks { }
            if SlintNavigation.route[0] == "music": Music { }
            if SlintNavigation.route[0] == "settings": Settings { }
            if SlintNavigation.route[0] == "search": Search { }
            if SlintNavigation.route[0] == "details": Details {
                item-id: SlintNavigation.route[1];
                padding: 0px;
            }
            if SlintNavigation.route[0] == "player": Player {}
        }


    }




}
